plot4 <- function() {
        unzip("exdata-data-household_power_consumption.zip")
        plot4data <- read.table("household_power_consumption.txt",sep=";",header=TRUE,nrows=2075260,stringsAsFactors=FALSE)
        plot4data$Time<-strptime(paste(plot4data$Date,plot4data$Time),"%d/%m/%Y %H:%M:%S")
        plot4data$Date <- as.Date(plot4data$Date,"%d/%m/%Y")
        plot4data$Global_active_power <- as.numeric(plot4data$Global_active_power)
        plot4data <- subset(plot4data,(Date=="2007-02-01" | Date=="2007-02-02"))
        png(file="plot4.png",width=480,height=480)
        par(mfrow=c(2,2))
        plot(plot4data$Time,plot4data$Global_active_power,type="n",xlab="",ylab="Global Active Power (kilowatts)")
        lines(plot4data$Time,plot4data$Global_active_power,type="l")
        plot(plot4data$Time,plot4data$Voltage,type="n",xlab="datetime",ylab="Voltage")
        lines(plot4data$Time,plot4data$Voltage,type="l")
        plot(plot4data$Time,plot4data$Sub_metering_1,type="l",xlab="",ylab="Energy sub metering",col="black")
        lines(plot4data$Time,plot4data$Sub_metering_2,type="l",col="red")
        lines(plot4data$Time,plot4data$Sub_metering_3,type="l",col="blue")
        legend("topright",legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lwd=2,bty="n")
        plot(plot4data$Time,plot4data$Global_reactive_power,type="n",xlab="datetime",ylab="Global_reactive_power")
        lines(plot4data$Time,plot4data$Global_reactive_power,type="l")
        dev.off()
}
